"""Add created column to tasks

Revision ID: 0122f9fa1bcb
Revises: aa9af6064728
Create Date: 2025-07-25 14:14:48.561758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0122f9fa1bcb'
down_revision: Union[str, Sequence[str], None] = 'aa9af6064728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('tasks', 'reminded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_tasks_due_at'), 'tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_index(op.f('ix_tasks_user_email'), 'tasks', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_email'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_at'), table_name='tasks')
    op.alter_column('tasks', 'reminded',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created')
    # ### end Alembic commands ###
